chriskempson/base16

README.md

- I intent to keep the template for Prism in sync with the new [prism-themes repo](https://github.com/prismjs/Prism-Themes) (_on which I also participate_)
- Removed end of line characters

added attribution for maintaining of template for Prism

---

README.md
scheme-previews/base16-ashes.html
scheme-previews/base16-ashes.svg
scheme-previews/base16-embers.html
scheme-previews/base16-embers.svg

Themes Ashes and Embers added to schemes from base16-builder

Updated with base16-builder

---

scheme-previews/base16-ateliersulphurpool.html
scheme-previews/base16-ateliersulphurpool.svg

Purplish colorscheme, [see also on demo](http://atelierbram.github.io/syntax-highlighting/atelier-schemes/sulphurpool/), part of the Atelier-schemes serie.

Atelier Schemes: new colorscheme in serie, Sulphurpool

---

scheme-previews/base16-atelierplateau.html
scheme-previews/base16-atelierplateau.svg

Warm colorscheme with desaturated colors, [see also on demo](http://atelierbram.github.io/syntax-highlighting/atelier-schemes/plateau/), part of the Atelier-schemes serie.

Atelier Schemes: new colorscheme in serie, Plateau

---

scheme-previews/base16-ateliercave.html
scheme-previews/base16-ateliercave.svg

Warm/cool colorscheme; violet as base-color [see also on demo](http://atelierbram.github.io/syntax-highlighting/atelier-schemes/cave/), part of the Atelier-schemes serie.

Atelier Schemes: new colorscheme in serie, Cave

---

scheme-previews/base16-ateliersavanna.html
scheme-previews/base16-ateliersavanna.svg

Understated colorscheme with desaturated colors; green as base-color [see also on demo](http://atelierbram.github.io/syntax-highlighting/atelier-schemes/savanna/), part of the Atelier-schemes serie.

Atelier Schemes: new colorscheme in serie, Savanna

---

scheme-previews/base16-atelierestuary.html
scheme-previews/base16-atelierestuary.svg

Colorscheme with reduced tonal-contrast between foreground colors; yellow/green as base-color [see also on demo](http://atelierbram.github.io/syntax-highlighting/atelier-schemes/estuary/), part of the Atelier-schemes serie.

Atelier Schemes: new colorscheme in serie, Estuary

---

README.md

For good measure, I added a link to my Terminal template.

Added Terminal.app to README

---

README.md

chriskempson/base16-templates-source#4

xfce4 theme template selectable from GUI

---

builder.md

Couple Typos in Builder Guide

---

styling.md

Correct "variations" typo

---

README.md

Add link to preview themes

---

README.md

I tried giving this a spin in Ruby, I have some issues with cloning speed that I'll work on fixing in the future.

Add base16-builder-ruby

---

README.md

This goes with the addition to the templates repo here: https://github.com/chriskempson/base16-templates-source/pull/23

Add Alacritty repo and aaron-williamson as maintainer

---

README.md

to: @chriskempson 
cc: @ewang12

Add the Circus theme

---

README.md

Contains four themes based on https://github.com/equinusocio/material-theme

Add base16-materialtheme-scheme

---

README.md

See nhurden/base16-builder-clojure#1

base16-builder-clojure updated to 0.9.0

---

README.md

moved base16-dracula to official dracula project

moved dracula repository

---

README.md

Related pr: https://github.com/chriskempson/base16-templates-source/pull/34

add conemu template

---

README.md

@chriskempson, I am not sure if this is not listed due to an oversight or not?

add iTerm2 template

---

README.md

To finish it off.  Thanks again!

Add JOE template

---

README.md

related to https://github.com/chriskempson/base16-unclaimed-schemes/pull/4

Add Codeschool to scheme list

---

README.md

Related to chriskempson/base16-templates-source#40

Add kitty template to template list

---

builder.md
file.md
styling.md

Just fixed a few things as I found them.

Fix some typos and grammar

---

README.md

Matching PR is in base16-templates-source

Add template repository for the Windows concfg utility

---

README.md

Another PR: https://github.com/chriskempson/base16-schemes-source/pull/35

Add snazzy scheme

---

README.md

Related PR https://github.com/chriskempson/base16-templates-source/pull/47

Add base16-xshell template

---

README.md

[Termux](https://github.com/termux/) is an Android app offering a full GNU/Linux environment without root.

Add Termux template

---

README.md

You could transfer the repo instead to me, so we don't loose the tickets and such.

Forked xresources repo

---

README.md

Link to *base16-schemes-source* PR: https://github.com/chriskempson/base16-schemes-source/pull/51

Add espresso theme info

---

README.md

[base16-hardcore-scheme](https://github.com/callerc1/base16-hardcore-scheme) 🌈

Add base16-hardcore-scheme

---

README.md

Add Humanoid for base16
Light and dark color schemes with bright colors.

add Humanoid color scheme

---

README.md

merge only after accepting the https://github.com/chriskempson/base16-templates-source/pull/82

add luakit to readme

---

README.md

https://github.com/chriskempson/base16-templates-source/pull/81

Add link to Textadept template repo

---

README.md

chriskempson/base16-schemes-source#69

Add Pasque color scheme to list

---

README.md

https://github.com/chriskempson/base16-templates-source/pull/85

Add FlatColor gtk theme

---

README.md

First of all thanks for this awesome project which has made consistent styling so much easier for me!
If you don't mind I added the link to the template repository for [vimiv](https://github.com/karlch/vimiv-qt), my little image viewer project.

Add vimiv template repository

---

README.md

The corresponding PR on the schemes-source repo: https://github.com/chriskempson/base16-schemes-source/pull/68

Add Colors color scheme to the list

---

README.md

https://github.com/chriskempson/base16-schemes-source/pull/70

Add nebula scheme to readme

---

README.md

Matching pull request: https://github.com/chriskempson/base16-templates-source/pull/88

Added HexChat template

---

README.md

https://github.com/chriskempson/base16-schemes-source/pull/80

Add Silk scheme to readme

---

README.md

Hi there,
I'm just adding a base16 color scheme "Kimber" to the Scheme Repositories list in README.md.
Thank you for the great work on this project! Hope you are all well and safe during this period.

Add Kimber scheme to readme

---

README.md

I've updated my username on GitHub from aaron-williamson to aarowill, this PR updates the links to my repositories and profile to their new location.

Update username aaron-williamson to aarowill

---

README.md

See also https://github.com/chriskempson/base16-templates-source/pull/86

Add base16-wmaker to README

---

README.md

https://github.com/chriskempson/base16-templates-source/pull/87

Add polybar template to readme

---

README.md

base16 qualitative HCL color palette
https://www.reddit.com/r/unixporn/comments/hjzw5f/oc_qualitative_color_palette_for_ansi_terminal

Add Qualia to README.md

---

README.md

[chriskempson/base16-schemes-source#75](https://github.com/chriskempson/base16-schemes-source/pull/75)

Add Shades of Purple scheme to README.md

---

README.md

Color palette with a nice pink. https://github.com/b3nj5m1n/base16-pinky-scheme

Add pinky scheme to README.md

---

README.md

https://github.com/chriskempson/base16-schemes-source/pull/73

Add Sakura scheme to README.md
