LICENSE.md

Used the exact license base16-builder uses, I leave it up to you if you want to license this repo differently
Came across this because code-mirror references it as the original source for a color scheme.

Add a license, cross the t's, dot the i's etc

---

README.md

I've been working on an experimental builder written in Go. It's found a few case issues with the template repos, so I've opened bugs against them (or fixed them).

Add base16-builder-go

---

README.md

This goes along with https://github.com/chriskempson/base16-templates-source/pull/5

Change URL of emacs to match templates

---

README.md

This adds the Unikitty scheme, which is pending addition at chriskempson/base16-schemes-source#7.
This also fixes a formatting inconsistency in the scheme list (Mexico-Light was sharing a bullet point with Materia).

Update scheme list

---

README.md

The Omnifocus template depends on some builder extensions in base16-builder-clojure, so I haven't added the template to the template repository.

Add base16-omnifocus and base16-builder-clojure

---

README.md

Tried my hand at writing up a builder in Node.js. :)
I feel like I abstracted some stuff, and eventually ran with it too much, but it works.
Not too sure if I'm keen on the command being available globally, but it's pretty convenient.

Add base16-builder-node

---

css/styles.css
index.html
js/switch.js

Hi!
Love these color schemes, but as @dkniffin said in #93, it's always a pain to get the hex values.
So, I've basically added 2 little features:
1. You can copy a hex value by clicking on its block (above the preview).
2. You can copy the CSS (the stylesheet basically), a formatted version of it (without the background), a JSON version (`"baseX": "#hex"`), and a text version (`baseX #hex`)
From a user perspective, only this has changed:

Copy hex values to clipboard on GitHub pages

---

README.md

So here's an all-new Bash script that will manage templates on top of setting the theme globally. Once this is merged, I'll be removing base16-schemer completely.

Replaced base16-schemer with base16-manager

---

README.md

I wrote a script to help convert old Base16 templates to the new style, since I've run into a few that don't seem to have been updated yet.

Add base16-template-converter to resources

---

builder.md

I also made sure we were using `filename` rather than `file name` everywhere, but that could be reverse if the latter is preferred.

Update description of scheme-slug to reference the previous description

---

README.md

Add [base16-tilix](https://github.com/karlding/base16-tilix) repository to the template repositories list in the ``README``.

Add Tilix to template repositories list

---

README.md

Add https://github.com/kreeger/base16-xcode to the list of templates in the README, as it is listed in https://github.com/chriskempson/base16-templates-source/blob/master/list.yaml#L41

list maintained base16-xcode template repository

---

README.md

I've rehosted the unmaintained solarflare at https://github.com/mnussbaum/base16-solarflare-scheme, with the permission of @chuckharmston the original author.
This PR adds it to the scheme list
Accompanies https://github.com/chriskempson/base16-schemes-source/pull/30 and https://github.com/chriskempson/base16-unclaimed-schemes/pull/5

Add solarflare scheme

---

README.md

I realised that there were some aspects of the base16 solarized schemes that I didn't like (such as the statusline in solarized light), so I went to submit a pull request to the owner, but found out that the schemes were unmaintained! So I copied the files from the unclaimed-schemes repo into my own one, and have updated the readme. I will also remove the solarized schemes from the unclaimed schemes repo.

Add solarized as one of the maintained schemes

---

README.md

Please add [base16-qutebrowser](https://github.com/theova/base16-qutebrowser) to the list.
See chriskempson/base16-templates-source#45.

Add base16-qutebrowser

---

README.md

Depends on chriskempson/base16-templates-source#44. Only merge if that is.

Add base16-i3status-rust to the template list.

---

README.md
builder.md

This adds baseXX-hex-bgr and adds a recommendation to warn on conflicting files. I'd propose this would be listed as either 0.9.1 or 0.10.0 (as there are new variables - either would be fine with semver because it's not a backwards breaking change), but I'm not sure if there are any other ideas we want to get in.

Various builder revisions

---

README.md

I updated the python builder to support base16 0.9.1

Add base16-builder-python to 0.9.1 builder list

---

README.md

Add a templates repository for Windows Terminal which is better-documented than the previously submitted ones.

Add link to Windows Terminal templates

---

README.md

Support for spec version 0.9.1 was implemented in [a recent commit](https://github.com/mnussbaum/base16-builder-ansible/commit/f63161458533d5dc1a75529fb4e1fb04bc6885e6)

base16-builder-ansible implements spec version 0.9.1

---

README.md

A separate pull request has already been created to add Sagelight to `list.yml` in `base16-schemes-source`.

Add Sagelight to Scheme Repositories in README.

---

README.md

Hello,
I just finished implementing my Rust base16 manager: https://github.com/Misterio77/flavours
The functionality is kinda a mix between base16-universal-manager and a builder (except it doesn't build to disk).
The main feature is applying schemes globally (based on your configuration, includes optional hooks) by specifying the scheme name, also supports glob matching, tab completions and a lot more. It's great for integrating into rofi menus and bar widgets (such as polybar). And it's _fast_.
Added a link to it on the readme

Add flavours to README

---

README.md

Reference: https://github.com/chriskempson/base16-templates-source/pull/99

Add Highlight.js to templates
